name: Create and publish a Docker image
on:
  release:
    types: [published]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build-and-push-image:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set ENV variables
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          buildkitd-config-inline: |
            [registry."10.0.0.113:5000"]
              http = true
              insecure = true
      - name: Build and push images
        uses: docker/bake-action@v4
        with:
          push: true
          set: |
            app.tags=${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.REPO_NAME }}:latest
            app.tags=${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.REPO_NAME }}:${{ github.ref_name }}
            app.cache-from=type=registry,ref=10.0.0.113:5000/${{ env.REPO_NAME }}_app:cache
            app.cache-to=type=registry,ref=10.0.0.113:5000/${{ env.REPO_NAME }}_app:cache